apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m6gkkcsoa-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:b2ffcf030b48aa3bfc687b377c5de3122a194e5f@sha256:70bce90c2beb7d49f05b9a06df1a1625a75c940d979d9bdffcba84e0937e8d03
          name: container-image
