apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: m6gkkcsoa-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/m6gkkcsoa-dotnet-basic-gitops